class RecordExample {

    public static void main(String args[]) {

        Point pointA = new Point(10, 50);

        System.out.println(pointA.x());
        System.out.println(pointA.y());

        Point pointB = new Point(10, 50);

        System.out.println(pointB.x());
        System.out.println(pointB.y());

        // Equals method is autogenerated for records
        if(pointA.equals(pointB)){
            System.out.println("Point A and Point B are equal");
        }

        // hashcode method is autogenerated for records
        System.out.print(pointA.hashCode());
    }
}

record Point(Integer x, Integer y) {}